import Head from 'next/head';
import { useEffect, useContext } from 'react';
import Layout from '../components/Layout';
import CardCollection from '../components/CardCollection';
import PostContext from '../components/PostContext';
import config from '../config';

export async function getServerSideProps(){
  
  const res = await fetch(config.url);
  const posts = await res.json();

  return {
    props: {
      posts
    }
  };
}

const Home = ({ posts }) => {

  const [state, setState] = useContext(PostContext);

  useEffect(() => {

    if(!state.posts.length){

      // Retrieve posts from local storage if any
      const storedPostsInString = localStorage.getItem("storedPosts");
      let storedPosts = [];
  
      if(storedPostsInString != null){
        storedPosts = JSON.parse(storedPostsInString);
      }
      
      // Updating posts with 'like' property and fixing image issue
      let updatedPosts = posts.map(post => {
        post.like = false;
        post.image = `${post.image}?lock=${post.id}`;
        return post;
      });

      setState({
        posts: [...updatedPosts, ...storedPosts]
      });

    }

  }, []);

  return (
    <div>
      <Layout home>
        <Head>
          <title>Moony Challenge</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <CardCollection posts={state.posts} />
      </Layout>
    </div>
  );
}

export default Home;