import Head from 'next/head';
import { useEffect, useContext } from 'react';
import PostContext from '../components/PostContext';
import CardCollection from '../components/CardCollection';
import config from '../config';

export async function getServerSideProps(){
  
  const res = await fetch(config.url);
  const posts = await res.json();

  return {
    props: {
      posts
    }
  };
}

const Home = ({ posts }) => {

  const [state, setState] = useContext(PostContext);

  useEffect(() => {

    if(!state.posts.length){
      // Updating posts with 'like' property
      let updatedPosts = posts.map(post => {
        post.like = false;
        return post;
      });

      setState({
        ...state,
        posts: updatedPosts
      });
    }

  }, []);

  return (
    <div>
      <Head>
        <title>Moony Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CardCollection posts={state.posts} />
      {console.log(state.posts)}
    </div>
  );
}

export default Home;